version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:9-jdk-sid-node-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - gradle-{{ checksum "build.gradle" }}
            - run: gradle assemble
            - run: gradle test

test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
        - bash <(curl -s https://codecov.io/bash)
